### ISSUE TITLE
Login access token issue

### ISSUE THREAD

**Issue by ricardochaidez** [unifilabs/UNIFI-ProjectAnalytics-API-Sample#3]
Looks like the login response in the API changed. Code needs to reflect this too.

![image](https://user-images.githubusercontent.com/5808512/72099259-1cc02a00-32d5-11ea-8a3d-80d45a3d482f.png)

**Comment by ricardochaidez** [comment]
Pull request associated with this issue

https://github.com/unifilabs/UNIFI-ProjectAnalytics-API-Sample/pull/4

**Comment by matthewcmorgan** [comment]
This has been merged, thank you.
